---
title: "preprocessing"
output: pdf_document
date: "`r Sys.Date()`"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Preprocessing

## Load data

```{r}
data <- read.csv("data_with10NA.csv", stringsAsFactors = T)
```

## Declare categorical variables

### Identify which categorical are not recognized by the system yet

```{r}
names(data)
class(data)
class(data[, 1])
sapply(data, class)
```

### Declare the categorical variables

```{r}
category_mappings <- list(
  Marital.status = list(
    levels = c(1, 2, 3, 4, 5, 6),
    labels = c(
      "single",
      "married",
      "widowed",
      "divorced",
      "facto union",
      "legally separated"
    )
  ),
  Application.order = list(
    levels = c(0, 1, 2, 3, 4, 5, 6, 9),
    labels = c(
      "first choice",
      "second choice",
      "third choice",
      "fourth choice",
      "fifth choice",
      "sixth choice",
      "seventh chioce",
      "last choice"
    )
  ),
  Course = list(
    levels = c(
      33,
      171,
      8014,
      9003,
      9070,
      9085,
      9119,
      9130,
      9147,
      9238,
      9254,
      9500,
      9556,
      9670,
      9773,
      9853,
      9991
    ),
    labels = c(
      "Biofuel Production Technologies",
      "Animation and Multimedia Design",
      "Social Service (evening attendance)",
      "Agronomy",
      "Communication Design",
      "Veterinary Nursing",
      "Informatics Engineering",
      "Equinculture",
      "Management",
      "Social Service",
      "Tourism",
      "Nursing",
      "Oral Hygiene",
      "Advertising and Marketing Management",
      "Journalism and Communication",
      "Basic Education",
      "Management (evening attendance)"
    )
  ),
  Daytime.evening.attendance = list(
    levels = c(0, 1),
    labels = c("evening", "daytime")
  ),
  Previous.qualification = list(
    levels = c(1, 2, 3, 4, 5, 6, 9, 10, 12, 14, 15, 19, 38, 39, 40, 42, 43),
    labels = c(
      "Secondary education",
      "Higher education - bachelor's degree",
      "Higher education - degree",
      "Higher education - master's",
      "Higher education - doctorate",
      "Frequency of higher education",
      "12th year of schooling - not completed",
      "11th year of schooling - not completed",
      "Other - 11th year of schooling",
      "10th year of schooling",
      "10th year of schooling - not completed",
      "Basic education 3rd cycle (9th/10th/11th year) or equiv.",
      "Basic education 2nd cycle (6th/7th/8th year) or equiv.",
      "Technological specialization course",
      "Higher education - degree (1st cycle)",
      "Professional higher technical course",
      "Higher education - master (2nd cycle)"
    )
  ),
  Nacionality = list(
    levels = c(
      1,
      2,
      6,
      11,
      13,
      14,
      17,
      21,
      22,
      24,
      25,
      26,
      32,
      41,
      62,
      100,
      101,
      103,
      105,
      108,
      109
    ),
    labels = c(
      "Portuguese",
      "German",
      "Spanish",
      "Italian",
      "Dutch",
      "English",
      "Lithuanian",
      "Angolan",
      "Cape Verdean",
      "Guinean",
      "Mozambican",
      "Santomean",
      "Turkish",
      "Brazilian",
      "Romanian",
      "Moldova (Republic of)",
      "Mexican",
      "Ukrainian",
      "Russian",
      "Cuban",
      "Colombian"
    )
  ),
  Displaced = list(levels = c(0, 1), labels = c("no", "yes")),
  Educational.special.needs = list(levels = c(0, 1), labels = c("no", "yes")),
  Debtor = list(levels = c(0, 1), labels = c("no", "yes")),
  Gender = list(levels = c(0, 1), labels = c("female", "male")),
  Scholarship.holder = list(levels = c(0, 1), labels = c("no", "yes"))
)
```

### apply the mappings

```{r}
for (col in names(category_mappings)) {
  if (class(data[[col]]) == "integer") {
    data[[col]] <- factor(data[[col]], levels = category_mappings[[col]]$levels, labels = category_mappings[[col]]$labels)
    print(paste("Column", col, "has been converted to factor"))
  }
}
```

### Export the data

```{r}
summary(data)

write.csv(data, "data_categorical.csv", row.names = FALSE)
```

## Boxplot of numeric variables

```{r}
numeric_cols <- sapply(data, is.numeric)

for (col in names(data)[numeric_cols]) {
  boxplot(data[[col]], main = paste("Boxplot of", col))
  # hist(data[[col]], main=paste("Histogram of", col))
  # print(shapiro.test(data[[col]]))
}
```

## Eliminar outliers con IQR

```{r}
remove_outliers <- function(x) {
  qnt <- quantile(x, probs = c(.25, .75), na.rm = TRUE)
  H <- 1.5 * IQR(x, na.rm = TRUE)
  y <- x
  y[x < (qnt[1] - H)] <- NA
  y[x > (qnt[2] + H)] <- NA
  return(y)
}


data_without_outliers <- apply(data[, numeric_cols], 2, function(x) remove_outliers(x))
data_without_outliers <- na.omit(data_without_outliers)
data_without_outliers <- as.data.frame(data_without_outliers)
head(data_without_outliers)
```

## Normalize numeric data

### Boxplot after normalization

```{r}
for (col in names(data_without_outliers)) {
  boxplot(data_without_outliers[[col]], main = paste("Boxplot of", col))
}

summary(data_without_outliers)
```
